version: '3.8'

services:
  server:
    image: yadavkapil9560/queue-cure-server:latest
    container_name: queue-cure-server
    restart: always
    env_file: .env
    networks:
      - queue-cure-prod-network

  client:
    image: yadavkapil9560/queue-cure-client:latest
    container_name: queue-cure-client
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - queue-cure-prod-network

networks:
  queue-cure-prod-network:
    driver: bridge
